// Generated by CoffeeScript 1.6.2
(function() {
  var BaseValidator, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseValidator = (function(_super) {
    __extends(BaseValidator, _super);

    function BaseValidator() {
      _ref = BaseValidator.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    BaseValidator.type = "validator";

    /*
    */


    BaseValidator.prototype.init = function() {
      return this.field.mediator.on("pre validate", this._command(this.validate));
    };

    /*
    */


    BaseValidator.prototype._error = function(defaultMessage, next) {
      return next(new Error(this.options.message || defaultMessage));
    };

    /*
    */


    BaseValidator.prototype.validate = function(model, next) {};

    return BaseValidator;

  })(require("../base"));

  module.exports = BaseValidator;

}).call(this);
