// Generated by CoffeeScript 1.6.2
(function() {
  var Collection, flatten, toarray;

  toarray = require("toarray");

  Collection = require("./collection");

  flatten = require("flatten");

  module.exports = {
    test: function(options) {
      return options.validate;
    },
    create: function(options) {
      return new Collection(options, flatten(toarray(options.validate).map(function(validate) {
        var field;

        field = validate.field = options.field;
        return field.decorFactory.create(validate, function(clazz) {
          return clazz.type === "validator";
        });
      })).filter(function(decor) {
        return !!decor;
      }));
    }
  };

}).call(this);
