// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = require("../factory")([require("./explicit"), require("./required"), require("./sub"), require("./test"), require("./type")]);

}).call(this);
