// Generated by CoffeeScript 1.6.2
(function() {
  var RequiredDecor, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  RequiredDecor = (function(_super) {
    __extends(RequiredDecor, _super);

    function RequiredDecor() {
      this.validate = __bind(this.validate, this);      _ref = RequiredDecor.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    RequiredDecor.prototype.validate = function(model, next) {
      if (this.value(model) == null) {
        next(new Error("" + this.field.path + " must be present"));
      }
      return next();
    };

    /*
    */


    RequiredDecor.test = function(options) {
      return options.required;
    };

    RequiredDecor.create = function(options) {
      return new RequiredDecor(options);
    };

    return RequiredDecor;

  })(require("./base"));

  module.exports = RequiredDecor;

}).call(this);
