// Generated by CoffeeScript 1.6.2
(function() {
  var TypeDecor, type, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  type = require("type-component");

  TypeDecor = (function(_super) {
    __extends(TypeDecor, _super);

    function TypeDecor() {
      this.validate = __bind(this.validate, this);      _ref = TypeDecor.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    TypeDecor.prototype.validate = function(model, next) {
      var t, valid, value;

      value = this.value(model);
      if (value == null) {
        return next();
      }
      t = type(value);
      valid = t === this.options.type;
      switch (t) {
        case "number":
          valid = valid && !isNaN(value);
          break;
        case "string":
          valid = true;
      }
      if (!valid) {
        return next(new Error("" + this.field.path + " must be a " + this.options.type));
      } else {
        return next();
      }
    };

    /*
    */


    TypeDecor.test = function(options) {
      return options.type != null;
    };

    TypeDecor.create = function(options) {
      return new TypeDecor(options);
    };

    return TypeDecor;

  })(require("./base"));

  module.exports = TypeDecor;

}).call(this);
