// Generated by CoffeeScript 1.6.2
(function() {
  var BaseMapper, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseMapper = (function(_super) {
    __extends(BaseMapper, _super);

    function BaseMapper() {
      _ref = BaseMapper.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    BaseMapper.prototype.init = function() {
      BaseMapper.__super__.init.call(this);
      return this.field.mediator.on("pre map", this.map);
    };

    /*
    */


    BaseMapper.prototype.map = function(model, data, next) {
      return next(null, model, data);
    };

    return BaseMapper;

  })(require("../base"));

  module.exports = BaseMapper;

}).call(this);
