// Generated by CoffeeScript 1.6.2
(function() {
  var CollectionMapper, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  CollectionMapper = (function(_super) {
    __extends(CollectionMapper, _super);

    function CollectionMapper() {
      _ref = CollectionMapper.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    CollectionMapper.prototype.map = function(model, data, next) {};

    return CollectionMapper;

  })(require("./base"));

  module.exports = CollectionMapper;

}).call(this);
