// Generated by CoffeeScript 1.6.2
(function() {
  var VanillaMap, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  VanillaMap = (function(_super) {
    __extends(VanillaMap, _super);

    function VanillaMap() {
      _ref = VanillaMap.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    VanillaMap.prototype.init = function() {
      return this.field.mediator.on("map", function(model, next) {
        return next(null, model);
      });
    };

    /*
    */


    VanillaMap.test = function(options) {
      return true;
    };

    VanillaMap.create = function(options) {
      return new VanillaMap(options);
    };

    return VanillaMap;

  })(require("./base"));

  module.exports = VanillaMap;

}).call(this);
