// Generated by CoffeeScript 1.6.2
(function() {
  var SyncCollection, async,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  async = require("async");

  SyncCollection = (function(_super) {
    __extends(SyncCollection, _super);

    /*
    */


    function SyncCollection(options, _synchronizers) {
      this._synchronizers = _synchronizers;
      SyncCollection.__super__.constructor.call(this, options);
    }

    /*
    */


    SyncCollection.prototype.sync = function(options, next) {
      return async.eachSeries(this._synchronizers, (function(synchronizer, next) {
        return synchronizer.sync(options, next);
      }), next);
    };

    return SyncCollection;

  })(require("./base"));

  module.exports = SyncCollection;

}).call(this);
