// Generated by CoffeeScript 1.6.2
(function() {
  var SyncCollection,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  SyncCollection = (function(_super) {
    __extends(SyncCollection, _super);

    /*
    */


    function SyncCollection(options, _synchronizers) {
      this._synchronizers = _synchronizers;
    }

    /*
    */


    return SyncCollection;

  })(require("./base"));

}).call(this);
