// Generated by CoffeeScript 1.6.2
(function() {
  var SchemaPlugin;

  SchemaPlugin = (function() {
    /*
    */
    function SchemaPlugin(schema) {
      this.schema(schema);
    }

    /*
    */


    SchemaPlugin.prototype.schema = function(schema) {
      this.schema = schema;
    };

    /*
    */


    SchemaPlugin.prototype.field = function(field) {};

    /*
    */


    SchemaPlugin.prototype.model = function(model) {};

    /*
    */


    SchemaPlugin.prototype.watch = function(model, watcher, field) {};

    return SchemaPlugin;

  })();

  module.exports = SchemaPlugin;

}).call(this);
