// Generated by CoffeeScript 1.6.2
(function() {
  var Collection, toarray;

  toarray = require("toarray");

  Collection = require("./collection");

  module.exports = {
    test: function(options) {
      return options.validate;
    },
    create: function(options) {
      return new Collection(options, toarray(options.validate).map(function(validate) {
        var field;

        field = validate.field = options.field;
        return field._validatorFactory.create(validate);
      }));
    }
  };

}).call(this);
