// Generated by CoffeeScript 1.6.2
(function() {
  var Validator, validators, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  validators = require("./validators");

  Validator = (function(_super) {
    __extends(Validator, _super);

    function Validator() {
      _ref = Validator.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    Validator.prototype.schema = function(schema) {
      var _this = this;

      return schema.validate = function(model, next) {
        var _ref1;

        return (_ref1 = schema.root).validate.apply(_ref1, arguments);
      };
    };

    /*
    */


    Validator.prototype.field = function(field) {
      field._validatorFactory = validators;
      field._validator = validators.create(field.options);
      return field.validate = function(model, next) {
        return field._validator.test(model, next);
      };
    };

    /*
    */


    Validator.prototype.model = function(model) {
      var _this = this;

      return model.validate = function(next) {
        return model.schema.validate(model, next);
      };
    };

    return Validator;

  })(require("../base"));

  module.exports = function(schema) {
    return new Validator(schema);
  };

}).call(this);
