// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(classes) {
    return {
      create: function(options, test) {
        var clazz, _i, _len, _results;

        if (test == null) {
          test = (function() {
            return true;
          });
        }
        _results = [];
        for (_i = 0, _len = classes.length; _i < _len; _i++) {
          clazz = classes[_i];
          if (test(clazz) && clazz.test(options)) {
            _results.push(clazz.create(options));
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      }
    };
  };

}).call(this);
