// Generated by CoffeeScript 1.6.2
(function() {
  var decor;

  decor = {
    /*
     validators
    */

    explicitValidator: require("./validate/explicit"),
    typeValidator: require("./validate/type"),
    requiredValidator: require("./validate/required"),
    subValidator: require("./validate/sub"),
    testValidator: require("./validate/test"),
    /* 
      Sync
    */

    explicitSync: require("./sync/explicit"),
    rootSync: require("./sync/root"),
    bubbleSync: require("./sync/bubble"),
    subSync: require("./sync/sub"),
    /*
     Map
    */

    refMap: void 0,
    collectionMap: void 0,
    vanillaMap: require("./map/vanilla")
  };

  module.exports = {
    create: function(options, test) {
      var clazz, name, _results;

      if (test == null) {
        test = (function() {
          return true;
        });
      }
      _results = [];
      for (name in decor) {
        clazz = decor[name];
        if (!clazz) {
          continue;
        }
        if (test(clazz) && clazz.test(options)) {
          _results.push(clazz.create(options));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    }
  };

}).call(this);
