// Generated by CoffeeScript 1.6.2
(function() {
  var decor;

  decor = {
    explicitValidator: require("./validate/explicit"),
    typeValidator: require("./validate/type"),
    requiredValidator: require("./validate/required"),
    subValidator: require("./validate/sub"),
    testValidator: require("./validate/test")
  };

  module.exports = {
    create: function(options) {
      var clazz, name, _results;

      _results = [];
      for (name in decor) {
        clazz = decor[name];
        if (clazz.test(options)) {
          _results.push(clazz.create(options));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    }
  };

}).call(this);
