// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(schema) {
    var factories;

    factories = [];
    return {
      use: function(factory) {
        return factories.push(factory);
      },
      create: function(options, test) {
        var factory, _i, _len, _results;

        _results = [];
        for (_i = 0, _len = factories.length; _i < _len; _i++) {
          factory = factories[_i];
          _results.push(factory.create(options, test));
        }
        return _results;
      }
    };
  };

  module.exports.sync = require("./sync");

  module.exports.validate = require("./validate");

}).call(this);
