// Generated by CoffeeScript 1.7.0
(function() {
  var BaseValidator;

  BaseValidator = (function() {

    /*
     */
    function BaseValidator(options) {
      this.options = options;
      this.field = this.options.field;
    }


    /*
     */

    BaseValidator.prototype.test = function(model, next) {};


    /*
     */

    BaseValidator.prototype._error = function(defaultMessage, next) {
      return next(new Error(this.options.message || defaultMessage));
    };


    /*
     */

    BaseValidator.create = function(options) {
      return new this(options);
    };

    return BaseValidator;

  })();

  module.exports = BaseValidator;

}).call(this);
