// Generated by CoffeeScript 1.6.2
(function() {
  var CollectionValidator, async, type, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _ = require("underscore");

  async = require("async");

  type = require("type-component");

  CollectionValidator = (function(_super) {
    __extends(CollectionValidator, _super);

    /*
    */


    function CollectionValidator(options, _validator) {
      this._validator = _validator;
      CollectionValidator.__super__.constructor.call(this, options);
    }

    /*
    */


    CollectionValidator.prototype.test = function(context, values, next) {
      var _this = this;

      if (type(values) !== "array") {
        return next(new Error("" + values + " must be an array"));
      }
      return async.eachSeries(values, (function(value, next) {
        return _this._validator.test(context, value, next);
      }), next);
    };

    /*
    */


    CollectionValidator.test = function(options) {
      return options.collection;
    };

    CollectionValidator.create = function(options) {
      var ops;

      ops = _.extend({}, options);
      delete ops.collection;
      return new CollectionValidator(options, options.field._validatorFactory.create(ops));
    };

    return CollectionValidator;

  })(require("./base"));

  module.exports = CollectionValidator;

}).call(this);
