// Generated by CoffeeScript 1.7.0
(function() {
  var Multi, toarray;

  toarray = require("toarray");

  Multi = require("./multi");

  module.exports = {
    test: function(options) {
      return options.validate;
    },
    create: function(options) {
      return new Multi(options, toarray(options.validate).map(function(validate) {
        var field;
        field = validate.field = options.field;
        return field._validatorFactory.create(validate);
      }));
    }
  };

}).call(this);
