// Generated by CoffeeScript 1.6.2
(function() {
  var factories;

  factories = require("factories");

  module.exports = factories.group([require("./test"), require("./explicit"), require("./sub"), require("./type"), require("./required")], [], require("./collection"));

}).call(this);
