// Generated by CoffeeScript 1.7.0
(function() {
  var factories;

  factories = require("factories");

  module.exports = factories.group([require("./test"), require("./explicit"), require("./sub"), require("./collection"), require("./type"), require("./required")], [], require("./multi"));

}).call(this);
