// Generated by CoffeeScript 1.6.2
(function() {
  var MultipleValidators, async, toarray, type,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  async = require("async");

  toarray = require("toarray");

  type = require("type-component");

  MultipleValidators = (function(_super) {
    __extends(MultipleValidators, _super);

    /*
    */


    function MultipleValidators(options, _validators) {
      this._validators = _validators;
      MultipleValidators.__super__.constructor.call(this, options);
    }

    /*
    */


    MultipleValidators.prototype.test = function(context, value, next) {
      return async.eachSeries(this._validators, (function(validator, next) {
        return validator.test(context, value, next);
      }), next);
    };

    return MultipleValidators;

  })(require("./base"));

  module.exports = MultipleValidators;

}).call(this);
