// Generated by CoffeeScript 1.7.0
(function() {
  var RequiredValidator,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  RequiredValidator = (function(_super) {
    __extends(RequiredValidator, _super);

    function RequiredValidator() {
      return RequiredValidator.__super__.constructor.apply(this, arguments);
    }


    /*
     */

    RequiredValidator.prototype.test = function(context, value, next) {
      if (value == null) {
        next(new Error("" + this.field.path + " must be present"));
      }
      return next();
    };


    /*
     */

    RequiredValidator.test = function(options) {
      return options.required;
    };

    RequiredValidator.create = function(options) {
      return new RequiredValidator(options);
    };

    return RequiredValidator;

  })(require("./base"));

  module.exports = RequiredValidator;

}).call(this);
