// Generated by CoffeeScript 1.7.0
(function() {
  var TypeValidator, type,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  type = require("type-component");

  TypeValidator = (function(_super) {
    __extends(TypeValidator, _super);

    function TypeValidator() {
      return TypeValidator.__super__.constructor.apply(this, arguments);
    }


    /*
     */

    TypeValidator.prototype.test = function(context, value, next) {
      var t, valid;
      if (value == null) {
        return next();
      }
      t = type(value);
      valid = t === this.options.type;
      switch (t) {
        case "number":
          valid = valid && !isNaN(value);
          break;
        case "string":
          valid = true;
      }
      if (!valid) {
        return next(new Error("" + this.field.path + " must be a " + this.options.type));
      } else {
        return next();
      }
    };

    TypeValidator.test = function(options) {
      return options.type && !options.collection;
    };

    TypeValidator.create = function(options) {
      return new TypeValidator(options);
    };

    return TypeValidator;

  })(require("./base"));

  module.exports = TypeValidator;

}).call(this);
