// Generated by CoffeeScript 1.6.2
(function() {
  var BaseSync, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseSync = (function(_super) {
    __extends(BaseSync, _super);

    function BaseSync() {
      _ref = BaseSync.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    BaseSync.type = "sync";

    /*
    */


    BaseSync.prototype.init = function() {
      BaseSync.__super__.init.call(this);
      this.field.mediator.on("pre save", this._command(this.save));
      this.field.mediator.on("pre load", this._command(this.load));
      this.field.mediator.on("pre _load", this._command(this._load));
      return this.field.mediator.on("pre _save", this._command(this._save));
    };

    /*
    */


    BaseSync.prototype.load = function(model, next) {
      return this._load(model, next);
    };

    /*
    */


    BaseSync.prototype.save = function(model, next) {
      return this._save(model, next);
    };

    /*
    */


    BaseSync.prototype._load = function(model, next) {
      return next();
    };

    BaseSync.prototype._save = function(model, next) {
      return next();
    };

    return BaseSync;

  })(require("../base"));

  module.exports = BaseSync;

}).call(this);
