// Generated by CoffeeScript 1.6.2
(function() {
  var BubbleSync, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BubbleSync = (function(_super) {
    __extends(BubbleSync, _super);

    function BubbleSync() {
      _ref = BubbleSync.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    BubbleSync.prototype.load = function(model, next) {
      if (this.options.load) {
        return next();
      }
      return this.field.parent.mediator.execute("_load", model, next);
    };

    /*
    */


    BubbleSync.prototype.save = function(model, next) {
      if (this.options.load) {
        return next();
      }
      return this.field.parent.mediator.execute("_save", model, next);
    };

    /*
    */


    BubbleSync.test = function(options) {
      return !options.load || !options.save;
    };

    BubbleSync.create = function(options) {
      return new BubbleSync(options);
    };

    return BubbleSync;

  })(require("./base"));

  module.exports = BubbleSync;

}).call(this);
