// Generated by CoffeeScript 1.6.2
(function() {
  var ExplicitSync, outcome, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  outcome = require("outcome");

  ExplicitSync = (function(_super) {
    __extends(ExplicitSync, _super);

    function ExplicitSync() {
      this._map = __bind(this._map, this);      _ref = ExplicitSync.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    ExplicitSync.prototype._load = function(model, next) {
      var _this = this;

      if (!this.options.load) {
        return next();
      }
      return this.options.load(model, outcome.e(next).s(function(data) {
        return _this._map(model, data, next);
      }));
    };

    /*
    */


    ExplicitSync.prototype._save = function(model, next) {
      var _this = this;

      if (!this.options.save) {
        return next();
      }
      return this.options.save(model, outcome.e(next).s(function(data) {
        return _this._map(model, data, next);
      }));
    };

    /*
    */


    ExplicitSync.prototype._map = function(model, data, next) {
      var _this = this;

      model.rawData = data;
      return this.field.mediator.execute("map", model, outcome.e(next).s(function(model) {
        if (!_this.field.parent) {
          model.set(model.rawData);
        } else {
          model.set(_this.field.path, model.rawData);
        }
        return next();
      }));
    };

    /*
    */


    ExplicitSync.test = function(options) {
      return options.load || options.save;
    };

    ExplicitSync.create = function(options) {
      return new ExplicitSync(options);
    };

    return ExplicitSync;

  })(require("./base"));

  module.exports = ExplicitSync;

}).call(this);
