// Generated by CoffeeScript 1.6.2
(function() {
  var RootSync, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  RootSync = (function(_super) {
    __extends(RootSync, _super);

    function RootSync() {
      _ref = RootSync.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    RootSync.prototype.setupModel = function(model) {
      var _this = this;

      model.memoizer = void 0;
      return model.on("watching", function(property) {
        var _ref1;

        return (_ref1 = _this.field.child(property, true)) != null ? _ref1.mediator.execute("watching", model) : void 0;
      });
    };

    /*
    */


    RootSync.test = function(options) {
      return !options.field.parent;
    };

    RootSync.create = function(options) {
      return new RootSync(options);
    };

    return RootSync;

  })(require("./base"));

  module.exports = RootSync;

}).call(this);
