// Generated by CoffeeScript 1.6.2
(function() {
  var SubSync, async, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  async = require("async");

  SubSync = (function(_super) {
    __extends(SubSync, _super);

    function SubSync() {
      _ref = SubSync.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    SubSync.prototype.load = function(model, next) {
      return this._exec(model, "load", next);
    };

    /*
    */


    SubSync.prototype.save = function(model, next) {
      return this._exec(model, "save", next);
    };

    /*
    */


    SubSync.prototype._exec = function(model, command, next) {
      return async.eachSeries(this.field.fields, (function(field, next) {
        return field.mediator.execute(command, model, next);
      }), next);
    };

    /*
    */


    SubSync.test = function(options) {
      return false;
    };

    SubSync.create = function(options) {
      return new SubSync(options);
    };

    return SubSync;

  })(require("./base"));

  module.exports = SubSync;

}).call(this);
