// Generated by CoffeeScript 1.6.2
(function() {
  var BindableSchema, Plugins, bindable, field;

  field = require("./field");

  bindable = require("bindable");

  Plugins = require("./plugins");

  BindableSchema = (function() {
    /*
    */
    function BindableSchema(definition) {
      this.plugins = new Plugins();
      this.root = field(this.plugins, definition);
    }

    /*
    */


    BindableSchema.prototype.use = function(plugin) {
      return this.plugins.push(plugin);
    };

    /*
    */


    BindableSchema.prototype.attach = function(target) {
      var fieldInfo;

      fieldInfo = new bindable.Object();
      this.root.attach(target, fieldInfo);
      return fieldInfo;
    };

    return BindableSchema;

  })();

  module.exports = function(definition) {
    return new BindableSchema(definition);
  };

}).call(this);
