// Generated by CoffeeScript 1.6.2
(function() {
  var BindableSchema, bindable, decor, field;

  field = require("./field");

  decor = require("./field/decor");

  bindable = require("bindable");

  BindableSchema = (function() {
    /*
    */
    function BindableSchema(definition) {
      this.root = field(definition);
      this.root.use(decor);
    }

    /*
    */


    BindableSchema.prototype.use = function(decor) {
      return this.root.use(decor);
    };

    return BindableSchema;

  })();

  module.exports = function(definition) {
    return new BindableSchema(definition);
  };

}).call(this);
