// Generated by CoffeeScript 1.6.2
(function() {
  var BindableSchema, bindable, decor, field;

  field = require("./field");

  decor = require("./field/decor");

  bindable = require("bindable");

  BindableSchema = (function() {
    /*
    */
    function BindableSchema(definition) {
      this.root = field(definition, this);
      this.decor = decor(this);
      this.use(decor.validate);
      this.use(decor.sync);
    }

    /*
    */


    BindableSchema.prototype.use = function(decor) {
      this.decor.use(decor);
      return this.root.use(decor);
    };

    /*
     setups a model
    */


    BindableSchema.prototype.setupModel = function(model) {
      return this.root.setupModel(model);
    };

    return BindableSchema;

  })();

  module.exports = function(definition) {
    return new BindableSchema(definition);
  };

  module.exports.validate = decor.validate;

  module.exports.sync = decor.sync;

}).call(this);
