// Generated by CoffeeScript 1.6.2
(function() {
  var Plugins;

  Plugins = (function() {
    /*
    */
    function Plugins() {
      this._plugins = [];
    }

    /*
    */


    Plugins.prototype.push = function(plugin) {
      return this._plugins.push(plugin);
    };

    /*
    */


    Plugins.prototype.attach = function(target, info, field) {
      var plugin, _i, _len, _ref, _results;

      _ref = this._plugins;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        plugin = _ref[_i];
        _results.push(plugin.attach(target, info, field));
      }
      return _results;
    };

    return Plugins;

  })();

  module.exports = Plugins;

}).call(this);
