// Generated by CoffeeScript 1.6.2
(function() {
  var BaseDecor,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  BaseDecor = (function() {
    /*
    */
    function BaseDecor(options) {
      this.options = options;
      this.value = __bind(this.value, this);
      this.field = options.field;
      this.init();
    }

    /*
    */


    BaseDecor.prototype.init = function() {};

    /*
    */


    BaseDecor.prototype.value = function(model) {
      return model.get(this.field.path);
    };

    return BaseDecor;

  })();

  module.exports = BaseDecor;

}).call(this);
