// Generated by CoffeeScript 1.6.2
(function() {
  var BaseDecor,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  BaseDecor = (function() {
    /*
    */
    function BaseDecor(options) {
      this.options = options;
      this.setupModel = __bind(this.setupModel, this);
      this.value = __bind(this.value, this);
      this.field = options.field;
      this.field.on("setupModel", this.setupModel);
      this.init();
    }

    /*
    */


    BaseDecor.prototype.init = function() {};

    /*
    */


    BaseDecor.prototype.value = function(model) {
      return model.get(this.field.path);
    };

    /*
    */


    BaseDecor.prototype.setupModel = function(model) {};

    /*
    */


    BaseDecor.prototype._command = function(fn) {
      var _this = this;

      return function(model, next) {
        return fn.call(_this, model, function(err) {
          if (err != null) {
            return next(err);
          }
          return next(null, model);
        });
      };
    };

    return BaseDecor;

  })();

  module.exports = BaseDecor;

}).call(this);
